### ISSUE TITLE
Compiling error on Ubuntu 21.04

### ISSUE THREAD

**Issue by Eydcao** [FloSewn/tmesh#3]
Dear there,

I am trying to compile this project on a Ubuntu 21.04 machine but the below error happens.

Any hints :>?

![image](https://user-images.githubusercontent.com/48085697/146279573-58a51d68-3b8a-4ea2-9b1c-65b39694a381.png)

----copy of the log----

➜  tmesh git:(master) cd build 
➜  build git:(master) cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yadi/opt/tmesh/build
➜  build git:(master) make
Consolidate compiler generated dependencies of target tmesh
[ 54%] Built target tmesh
Consolidate compiler generated dependencies of target TMesh
[ 63%] Built target TMesh
Consolidate compiler generated dependencies of target tmesh_test
[ 68%] Linking C executable tmesh_test
/usr/bin/ld: CMakeFiles/tmesh_test.dir/test/tmParam_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: multiple definition of `tests_run'; CMakeFiles/tmesh_test.dir/test/tmList_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: first defined here
/usr/bin/ld: CMakeFiles/tmesh_test.dir/test/tmesh_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: multiple definition of `tests_run'; CMakeFiles/tmesh_test.dir/test/tmList_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: first defined here
/usr/bin/ld: CMakeFiles/tmesh_test.dir/test/tmesh_examples.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: multiple definition of `tests_run'; CMakeFiles/tmesh_test.dir/test/tmList_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: first defined here
/usr/bin/ld: CMakeFiles/tmesh_test.dir/test/geom_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: multiple definition of `tests_run'; CMakeFiles/tmesh_test.dir/test/tmList_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: first defined here
/usr/bin/ld: CMakeFiles/tmesh_test.dir/test/unit_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: multiple definition of `tests_run'; CMakeFiles/tmesh_test.dir/test/tmList_tests.c.o:/home/yadi/opt/tmesh/src/tmesh/include/tmesh/minunit.h:10: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [src/tmesh/CMakeFiles/tmesh_test.dir/build.make:194: src/tmesh/tmesh_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:154: src/tmesh/CMakeFiles/tmesh_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
➜  build git:(master)

**Comment by FloSewn** [comment]
Hey there, I might have fixed that bug. Could you pull the newest commit in the master branch and check, if the error still appears?

Thank you!

**Comment by Eydcao** [comment]
Fixed thank you ;)
