### ISSUE TITLE
ERROR with file format

### ISSUE THREAD

**Issue by Diiiiii-9** [FloSewn/tmesh#4]
Hi, I got error when using that code.

I tried to mesh a graph(A rectangle with a center cut out) like :
```C
-------------
|   ---     |
|  |   |    |
|   ---     |
-------------
```
Here's my imput file:
```
Global element size: 5
Number of quadtree elements: 50
Mesh bounding box: -10.0, -10.0, 1000.0, 1000.0

Define nodes:
5 5
5 200
200 200
200 5
20 20
20 100
100 100
100 20
End nodes

Define exterior boundary: 1
0, 1, 0, 1.5
1, 2, 0, 1.5
2, 3, 0, 1.5
3, 0, 0, 1.5
End exterior boundary

Define interior boundary: 1
7, 6, 1, 1.5
6, 5, 1, 1.5
5, 4, 1, 1.5
4, 7, 1, 1.5
End interior boundary
```

Is there a format error in my input file?
（The sample input file you provided works on my computer)

Here's error message:
![image](https://user-images.githubusercontent.com/73735669/229049796-2d1cc3d2-56dd-44d8-90ff-89ae33fba9a8.png)

The program crashes here:
![image](https://user-images.githubusercontent.com/73735669/229050108-d4c81e5c-52ba-4caa-bc5f-7c70d1e4f1b4.png)

**Comment by FloSewn** [comment]
Hey there,
 
Thanks for using tmesh :)

It looks like you are defining the exterior boundary vertices in clockwise direction but tmesh requires their direction to be counter-clockwise (in contrast to interior boundaries - they must be defined clockwise).

Try to change these lines:

Define exterior boundary: 1
0, 3, 0, 1.5
3, 2, 0, 1.5
2, 1, 0, 1.5
1, 0, 0, 1.5
End exterior boundary

Alternatively, you could also change the coordinates of the first four vertices.

Let me know if it works ;-)

Greetings 
Flo

**Comment by Diiiiii-9** [comment]
Hi Flo,

Thanks for your reply :D

I tried changing the direction of the boundaries in the input file to match your description, but it still failed. 

![image](https://user-images.githubusercontent.com/73735669/229275042-73dc13e7-3ba9-487c-b43b-bc2942bf2315.png)


Here is my input file:

```
Global element size: 5
Number of quadtree elements: 50
Mesh bounding box: -10.0, -10.0, 1000.0, 1000.0

Define nodes:
5 5
5 200
200 200
200 5
50 50
50 100
100 100
100 50
End nodes

Define exterior boundary: 1
3, 2, 0, 1.5
2, 1, 0, 1.5
1, 0, 0, 1.5
0, 3, 0, 1.5
End exterior boundary

Define interior boundary: 1
4, 5, 1, 1.5
5, 6, 1, 1.5
6, 7, 1, 1.5
7, 4, 1, 1.5
End interior boundary
```

Best
Di

**Comment by FloSewn** [comment]
Hey there,

I checked the input file and noticed, that there were missing commas for the separation of the x and y coordinates of vertices.

This input file should work ;-)


```
 Global element size: 5
 Number of quadtree elements: 50
 Mesh bounding box: -10.0, -10.0, 1000.0, 1000.0
 
 Define nodes:
 5, 5
 5, 200 
 200, 200 
 200, 5
 50, 50
 50, 100 
 100, 100 
 100, 50
 End nodes
 
 Define exterior boundary: 1
 3, 2, 0, 1.5 
 2, 1, 0, 1.5 
 1, 0, 0, 1.5 
 0, 3, 0, 1.5 
 End exterior boundary
 
 Define interior boundary: 1
 4, 5, 1, 1.5 
 5, 6, 1, 1.5 
 6, 7, 1, 1.5 
 7, 4, 1, 1.5 
 End interior boundary

```

Greetings
Flo

**Comment by Diiiiii-9** [comment]
Hey there,

Thanks for being so patient with me on Github. I can't believe I missed such a small mistake! I appreciate your help and I'll be more careful next time.

Cheers,
Di

**Comment by FloSewn** [comment]
Don't worry - I recognized, that we definitely need better error messages for cases like this! Unfortunately I do not have much time for this project at the moment. 

Anyway - its great to hear of someone using it :-)

Feel free to ask any more questions!

Greetings
Flo
