### ISSUE TITLE
Dependencies and questions

### ISSUE THREAD

**Issue by ramcdona** [FloSewn/tmesh#5]
Is there a mailing list or forum for asking questions about TMesh and TQMesh?  I hate asking questions in an issue report if there is a better place.

I am considering replacing Triangle in my project with something else -- both because of the problematic Triangle license and also because Triangle crashes inelegantly.  Triangle appears to be abandoned, there is no evidence of continuing effort to fix its problems.  I have tried several wrappers that aim to improve the error handling situation, but those all seem to fall short as well.

I am attracted to TMesh because it has the ability to do mesh generation (not just CDT) and also its relatively limited list of dependencies.  I see that the libraries are embedded in the code directly, so they don't really introduce dependencies or cause additional build system headaches.  They are probably fine, but I suspect TinyExpr is only needed for specifying mesh density functions (and could possibly be made optional) and the Better String Library could probably also be made optional -- I don't expect a mesh generator do be doing highly complex operations with strings.  I will worry about this down the line.

How robust is TMesh?  Has it been run on a wide variety of cases like TriWild?  When errors are encountered, how are they handled?  Triangle simply exit()'s on error (killing your program), and there are also cases where pointers are used without safety checks that simply cause segfaults (crashing your program).

Is TMesh actively developed?  If issues are encountered, how actively are they addressed?  Are patches accepted?

**Comment by FloSewn** [comment]
Hey there,

thanks for your interest! Unfortunately I don't have a mailing list or something similar yet - but it is a good idea.

Thanks also for considering TMesh for your work - I really appreciate that. 
The limited number of dependencies was definitely a motivation in the implementation, as I was also looking for a meshing program a few years ago that didn't rely on huge computational geomtry libraries.
The few dependencies you already mentioned could certainly be decoupled a bit more to make the code more self-contained - I really like that idea!

I have to admit, though, that I wrote Tmesh a few years ago out of interest in 2D meshing and the advancing front method - so I neglected things like error handling quite a bit back then. I also definitely didn't test it on as many test cases as TriWild.

At the moment I'm a bit busy - but in the near future I plan to work more on TMesh and TQMesh again. 
If you also want to improve something, I'm also very happy about contributions! 


Thanks again for your message and let me know, if I can help with anything.

Greetings
Flo

**Comment by ramcdona** [comment]
GitHub makes it pretty easy to add 'Discussions' to any repository.  You might consider that as a way to provide a forum for questions.

It looks like TQMesh can also run in triangle only mode - and it seems newer (to have fewer dependencies) and to be more recently developed.

Are you going to support both TMesh and TQMesh going forward?  Would it make more sense for me to adopt TQMesh even if I don't need the Q (at least for now)?

**Comment by FloSewn** [comment]
Hey there, 

sorry for my late response and thanks for the 'Discussions' hint - I will definitely add it :-)

Yes - I developed TQMesh more recently and will probably focus more on it than on TMesh in the near future.
It also features (at least a little) more error handling, as far as I remember - and I definitely plan to enhance it in that way. 

Greetings
Flo
